# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dhq < Formula
  desc "DeployHQ CLI — deploy from your terminal"
  homepage "https://www.deployhq.com"
  version "0.18.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deployhq/deployhq-cli/releases/download/v0.18.3/dhq_0.18.3_darwin_amd64.tar.gz"
      sha256 "ac51014652a75789563cc087c829956a9d8cb7b67cf25b4129b72a80d9f2bb96"

      define_method(:install) do
        bin.install "dhq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deployhq/deployhq-cli/releases/download/v0.18.3/dhq_0.18.3_darwin_arm64.tar.gz"
      sha256 "11b6b5aa4d93f3f31d5e05144069a6a11afd7108207b61d66993d2d641a571f8"

      define_method(:install) do
        bin.install "dhq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deployhq/deployhq-cli/releases/download/v0.18.3/dhq_0.18.3_linux_amd64.tar.gz"
      sha256 "417f7253ea00b5b2a09125c2a6e8bb4bf89d1f2b00273eb340159bd08e0c1bd7"
      define_method(:install) do
        bin.install "dhq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deployhq/deployhq-cli/releases/download/v0.18.3/dhq_0.18.3_linux_arm64.tar.gz"
      sha256 "7d3f4db67f98d7df969e48a0f31af2822b83ee2788a491ebbd9b401a66f0c3e4"
      define_method(:install) do
        bin.install "dhq"
      end
    end
  end

  test do
    system "#{bin}/dhq", "version"
  end
end
