# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dhq < Formula
  desc "DeployHQ CLI — deploy from your terminal"
  homepage "https://www.deployhq.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deployhq/deployhq-cli/releases/download/v0.4.0/dhq_0.4.0_darwin_amd64.tar.gz"
      sha256 "e7e1478a3c2e679380e18f81b738fd89c50141308570416cb043ba1986b0ea1d"

      define_method(:install) do
        bin.install "dhq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deployhq/deployhq-cli/releases/download/v0.4.0/dhq_0.4.0_darwin_arm64.tar.gz"
      sha256 "b32d531cce4ace06bc7e737a2cd21f4845b7091b7aec27596641ef5e99e192e5"

      define_method(:install) do
        bin.install "dhq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deployhq/deployhq-cli/releases/download/v0.4.0/dhq_0.4.0_linux_amd64.tar.gz"
      sha256 "cb6e79337553bfde13573e24a396ba6caf725541e26a8e90e45dd92dbd3fbb2e"
      define_method(:install) do
        bin.install "dhq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deployhq/deployhq-cli/releases/download/v0.4.0/dhq_0.4.0_linux_arm64.tar.gz"
      sha256 "6375878daee40bda51bbb9ef5981508ef1dcccb122a2ebde6800a2e251df0087"
      define_method(:install) do
        bin.install "dhq"
      end
    end
  end

  test do
    system "#{bin}/dhq", "version"
  end
end
